language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck

os:
  - linux
  - osx

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make

after_success:
  - make check
  - cppcheck --quiet *.h *.c tests/
